
apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
android {
    compileSdk rootProject.ext.android["compileSdkVersion"]

    defaultConfig {
        minSdk rootProject.ext.android["minSdkVersion"]
        targetSdk rootProject.ext.android["targetSdkVersion"]
        versionCode VERSION_CODE as int
        versionName VERSION_NAME

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += '-Xcontext-receivers'
    }
    dataBinding {
        enabled = true
    }
}


dependencies {

    rootProject.ext.androidDefaultDependencies.each {
        k, v -> implementation v
    }
    testImplementation rootProject.ext.test["junit"]
    androidTestImplementation rootProject.ext.test["ext"]
    androidTestImplementation rootProject.ext.test["espresso"]
}