apply from: "../common_lib_config.gradle"
android {
    namespace 'com.ym.viewframe'
    dataBinding {
        enabled = true
    }
    viewBinding {
        enabled = true
    }
}

dependencies {
    api project(path: ':libNetwork')
    api project(path: ':libStorage')
    api project(path: ':libResouce')
}