apply from: "../common_lib_config.gradle"

android {
    namespace 'com.ym.basic'
    dataBinding {
        enabled = true
    }
    viewBinding {
        enabled = true
    }
}

dependencies {

    api project(path: ':libRouter')

    api rootProject.ext.dependencies["multidex"]
    //jetpack库

//    api "org.jetbrains.kotlin:kotlin-stdlib:1.7.10"

//    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
//    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"

}